apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: content-web
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: content-web
    spec:
      containers:
      - name: content-web
        image: gordopremiumreg.azurecr.io/wth2/content-web
        env:
        - name: CONTENT_API_URL
          value: "http://content-api:3001"
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests: 
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: content-web
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: content-web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: content-api
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: gordopremiumreg.azurecr.io/wth2/content-api
        resources:
          limits:
            memory: "2Gi"
            cpu: "1000m"
          requests: 
            memory: "1Gi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: content-api
spec:
  type: LoadBalancer
  ports:
  - port: 3001
  selector:
    app: content-api