apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: content-web-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: content-web-v2
    spec:
      containers:
      - name: content-web-v2
        image: gordopremiumreg.azurecr.io/wth2/content-web-v2
        env:
        - name: CONTENT_API_URL
          value: "http://content-api-v2:3001"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests: 
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: content-web-v2
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: content-web-v2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: content-api-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: content-api-v2
    spec:
      containers:
      - name: content-api-v2
        image: gordopremiumreg.azurecr.io/wth2/content-api-v2
        env:
        - name: MONGODB_CONNECTION
          value: "mongodb://mongodb-mongodb:27017/contentdb"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests: 
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: content-api-v2
spec:
  type: LoadBalancer
  ports:
  - port: 3001
  selector:
    app: content-api-v2
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: content-init
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: content-init
    spec:
      containers:
      - name: content-init
        image: gordopremiumreg.azurecr.io/wth2/content-init
        env:
        - name: MONGODB_CONNECTION
          value: "mongodb://mongodb-mongodb:27017/contentdb"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests: 
            memory: "256Mi"
            cpu: "500m"